### ISSUE TITLE
support pytorch>=1.1.0 and cuda>=9.0?

### ISSUE THREAD

**Issue by ArcherFMY** [visinf/irr#1]
Hi,

Thanks for the great work!

Does this code support pytorch>=1.1.0 and cuda>=9.0?

**Comment by hurjunhwa** [comment]
Hi,

Yes, the code itself is working properly on pytorch >= 1.0.0 and cuda >= 9.0.
However, the correlation module needs to be adjusted accordingly.

First, move all files in `models/correlation_package_cu9` to `models/correlation_package` (overwritting),
Then, depending on your system, configure `-gencode`, `-ccbin`, `cuda-path` in models/correlation_package/setup.py accordingly.
Finally, you can install the correlation package (for cuda >= 9.0) by excuting `./install.sh`

Please let me know if it doesn't work!

**Comment by ArcherFMY** [comment]
Thanks for your reply.

It seems that the correlation op cannot be correctly install for pytorch1.1?

I got this error.

```
>>> import commandline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/archer/Research/DeepLearning/pytorch/irr/commandline.py", line 14, in <module>
    import models
  File "/media/archer/Research/DeepLearning/pytorch/irr/models/__init__.py", line 8, in <module>
    from . import pwcnet
  File "/media/archer/Research/DeepLearning/pytorch/irr/models/pwcnet.py", line 8, in <module>
    from .correlation_package.correlation import Correlation
  File "/media/archer/Research/DeepLearning/pytorch/irr/models/correlation_package/correlation.py", line 4, in <module>
    import correlation_cuda
ImportError: /home/archer/.local/lib/python3.5/site-packages/correlation_cuda-0.0.0-py3.5-linux-x86_64.egg/correlation_cuda.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
```

But I can install the correlation op using PyTorch-1.0&cuda-9.0. Actually, I am using FlowNet2 in this environment.

**Comment by ArcherFMY** [comment]
problem solved!

I created a new environment which just installed pytorch1.1.0 and then installed the correlation package first. It works properly.

Thanks!

**Comment by hurjunhwa** [comment]
Thanks for letting me know, and it's glad that it's working!
