### ISSUE TITLE
Saved check point for things3d_subset

### ISSUE THREAD

**Issue by Ecalpal** [visinf/irr#11]
Hi,
Why didn't you provide the check points after finetune in things3d_subset?
I think if there is one, it will make the whole training process clearer.
:)

**Comment by hurjunhwa** [comment]
Hi, 
Oh, right I forgot uploading it as well.
I will prepare it by the end of next week!

**Comment by Ecalpal** [comment]
Thanks!
I'm looking forward to these files.

**Comment by hurjunhwa** [comment]
Hi, 
I just uploaded the model trained on things3d-subset :)
When testing on SintelTrainingCleanFull, you will get:

Flow EPE = 1.8804
Occlusion F1 score = 0.7122

Best,
Jun

**Comment by Ecalpal** [comment]
> Hi,
> I just uploaded the model trained on things3d-subset :)
> When testing on SintelTrainingCleanFull, you will get:
> 
> Flow EPE = 1.8804
> Occlusion F1 score = 0.7122
> 
> Best,
> Jun

Thanks!
