### ISSUE TITLE
Questions about FlyingThings3D_subset

### ISSUE THREAD

**Issue by Blcony** [visinf/irr#12]
Hi~

Thanks for your wonderful work and codes!

I am a newcomer in the field of optical flow. So I am a littel confused about the meaning of the FlyingThings3D_subset. Should I download the datasets which are drawn by red lines in figure below directly? Or there are another download link that I haven't found?

![FlyingThins3D_subset](https://user-images.githubusercontent.com/26156941/65151691-2dfcd680-da59-11e9-9700-9abfe9658070.png)

Your reply will be very helpful for me, and I wish to hear from you soon!

Bset wishes!

Blcony

**Comment by hurjunhwa** [comment]
Hi Blcony,

Yes, when training on FlyingThings3D (after pre-training on FlyingChairsOcc), 
the data from those three links are exactly the one that we used.
For reproducing our model, you won't need other kinds of GT except those three.

Best,
Jun

**Comment by Blcony** [comment]
Hi Jun~

Thank you very much! For a newcomer like me, your reply means a lot!

Best wishes!

Blcony
