### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by eeedWard** [visinf/irr#14]
Hi

What inference speed should I (approximately) expect for the PWC_IRR model for an input image of 960,540,3?

On my RTX 2070 it runs at 1.5 FPS, is it supposed to be faster?

Thanks

**Comment by hurjunhwa** [comment]
Hi,

When testing the image with the resolution of 960x540x3, 
the speed is around 5 FPS on 1080 Ti.
Maybe a different installation setting for the correlation package would occur a bottleneck, but I am not so sure what causes delay at this moment..

Thanks
