### ISSUE TITLE
Hi,How to test large images？

### ISSUE THREAD

**Issue by 972461099** [visinf/irr#20]
Thanks for your share code,that's great.
But there is a problem, when I test large size images, the GPU is not enough.
So I cut the picture into four pieces 
and stitched them after testing. But the lines are obvious.
Could you tell me how to improve that?

![glt](https://user-images.githubusercontent.com/23586956/77154401-94c97e00-6ad6-11ea-9347-5ff27d9f7c06.JPG)

**Comment by hurjunhwa** [comment]
Hi,

If cropping the images into several pieces, it becomes more challenging to estimate optical flow especially when a corresponding pixel is in the other cropped image.
In this case, it would be better to resize the image into 1/4 or 1/16, and then estimate the flow.
There may be some accuracy drop (maybe for small objects), but it won't be too significant.
How big is your input image?

Best,
Jun

**Comment by 972461099** [comment]
My image is 2048 * 2048, , and my gpu is 24G,because I need the optical flow map as the feature map of my model. Thank you for your suggestions, I will try.
