### ISSUE TITLE
only one occlusion map 

### ISSUE THREAD

**Issue by zdw-qingdao** [visinf/irr#24]
I notice that in your paper there are two occlusion maps for the two inputs. But in the code I find there is only one occluision map output.
loss_dict_per_step, output_dict, batch_size = self._step(example_dict)
How can i obtain the two occlusion map at the same time?
Thank you!

**Comment by hurjunhwa** [comment]
Hi, 

As in here:
https://github.com/visinf/irr/blob/f0eba07773806941853d7cb7f7ad28307a288a20/models/IRR_PWC.py#L176

in the training time, you can access from output_dict:
- occlusion in the forward flow case: ``output_dict['occ'][-1][0]``
- occlusion in the backward flow case: ``output_dict['occ'][-1][1]``

In the evaluation or testing time,  the model outputs another dictionary ``output_dict_eval`` which only has the occlusion map in the forward flow case.
In this case, by returning ``output_dict``, you can still access the two occlusion maps.

Best,
Jun
