### ISSUE TITLE
Args Module

### ISSUE THREAD

**Issue by AliKafaei** [visinf/irr#26]
Thanks for your complete code. 
I want to use the network in my own code (not using in console command mode) so I need to load state dictionary and pass it to the network. The problem is that the network model needs an input argument args. Most of the args parameters can be ignored except args.modules(). After reading the code for several times; I couldent find any clue that what it is and how can I set it manually.
![Selection_001](https://user-images.githubusercontent.com/36259911/90323876-4610fa80-df35-11ea-867c-557f1c816168.png)

What should I set self.modules()?
Another issue is that scipy no longer supports imread and it must be replaced by cv2,imread.
Best,
Ali Kafaei

**Comment by hurjunhwa** [comment]
Hi,

In the original code, I used tqdm with a version of 4.24.0.
But using upto 4.40.0 will still work.

Regarding the self.module(), probably referring this will help:
https://discuss.pytorch.org/t/pytorch-self-module/49677/5

Yes, unfortunately scipy no longer support. 
Using cv2.imread or skimage.io.imread can be the good alternative as you metion.

Thanks,
Jun
