### ISSUE TITLE
occlusions_rev.zip download fail

### ISSUE THREAD

**Issue by BH4615** [visinf/irr#28]
I tried to download revised GT of MPI sintel. however the link refused to connect.
would you check the link still alive?

https://download.visinf.tu-darmstadt.de/data/flyingchairs_occ/occlusions_rev.zip

**Comment by hurjunhwa** [comment]
It seems like the download server is not working.
Here is the temporary download link:
https://drive.google.com/file/d/1reT7D06DdP2noXIjK-CFT-OxB8LmYUYr/view?usp=sharing
