### ISSUE TITLE
can't run correlation package on google colab

### ISSUE THREAD

**Issue by RokiaAbdeen** [visinf/irr#29]
I have tried to run the code on google colab using python 3.6, cuda 8.0 and pytorch 0.4.1 but get many errors related to torchvision and I have tried again to run it with newer versions of cuda (9.0 and 10) and pytorch (1.1) but got this error (no package called correlation_cuda) do you have any solution for correlation package problem please ?!

**Comment by hurjunhwa** [comment]
Hi,
Have you successfully installed the correlation package by running this?: 
https://github.com/visinf/irr/blob/master/install.sh

**Comment by RokiaAbdeen** [comment]
this is the output of the installation :

running install
running bdist_egg
running egg_info
writing correlation_cuda.egg-info/PKG-INFO
writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
writing top-level names to correlation_cuda.egg-info/top_level.txt
reading manifest file 'correlation_cuda.egg-info/SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'correlation_cuda' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c correlation_cuda.cc -o build/temp.linux-x86_64-3.6/correlation_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c correlation_cuda_kernel.cu -o build/temp.linux-x86_64-3.6/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 -ccbin /usr/bin/gcc-5 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.6/dist-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:352:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:359:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:369:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:461:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:473:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:490:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
correlation_cuda_kernel.cu: In lambda function:
correlation_cuda_kernel.cu:507:124: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
creating build/lib.linux-x86_64-3.6
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/correlation_cuda.o build/temp.linux-x86_64-3.6/correlation_cuda_kernel.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/correlation_cuda.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/correlation_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for correlation_cuda.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/correlation_cuda.py to correlation_cuda.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_cuda.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.correlation_cuda.cpython-36: module references __file__
creating dist
creating 'dist/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
creating /usr/local/lib/python3.6/dist-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
Extracting correlation_cuda-0.0.0-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
Adding correlation-cuda 0.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
Processing dependencies for correlation-cuda==0.0.0
Finished processing dependencies for correlation-cuda==0.0.0
/content/gdrive/My Drive/PWCFlowNet/PWC_IRR/models

**Comment by RokiaAbdeen** [comment]
I have used cuda 9.0 and torch 1.1, but when I am running the code I got this error

Traceback (most recent call last):
  File "/content/gdrive/My Drive/PWCFlowNet/PWC_IRR/main.py", line 5, in <module>
    import commandline
  File "/content/gdrive/My Drive/PWCFlowNet/PWC_IRR/commandline.py", line 12, in <module>
    import datasets
  File "/content/gdrive/My Drive/PWCFlowNet/PWC_IRR/datasets/__init__.py", line 1, in <module>
    from . import flyingchairs
  File "/content/gdrive/My Drive/PWCFlowNet/PWC_IRR/datasets/flyingchairs.py", line 7, in <module>
    from torchvision import transforms as vision_transforms
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 5, in <module>
    from .inception import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/inception.py", line 6, in <module>
    from torch.jit.annotations import Optional
ImportError: cannot import name 'Optional'

**Comment by RokiaAbdeen** [comment]
it works now with torch==1.1.0 and torchvision==0.3.0
thanks alot

**Comment by hurjunhwa** [comment]
Thanks for sharing!!
