### ISSUE TITLE
I got this error when I'm trying to save png during validation step to visualize and check the flow image

### ISSUE THREAD

**Issue by RokiaAbdeen** [visinf/irr#30]
![tt](https://user-images.githubusercontent.com/26867350/94634933-ff6c3980-0303-11eb-9384-4736a99b2ea9.png)

**Comment by hurjunhwa** [comment]
Hi,
Unfortunately, the current code doesn't support the recent version of pypng.
You can probably try the older version, by running ``pip install pypng==0.0.18``.

**Comment by RokiaAbdeen** [comment]
it didn't gave me any error when I change pypng to this older version
but on the other side, this is the result image for all frames
Note: I have used your saved pwc_net models for validation
![22](https://user-images.githubusercontent.com/26867350/94918657-93492b80-04e5-11eb-8991-e09ea65298bf.png)

**Comment by hurjunhwa** [comment]
That's the png image that is converted into the KITTI optical flow format.
Could you maybe put this flag at the end of the script?:
``--save_result_img``
This will convert the 2D optical flow map into the visualization format from the Middlebury dataset.

**Comment by RokiaAbdeen** [comment]
Ok, it works fine
thanks
