### ISSUE TITLE
Could you please show how to process KITTI images when inferring?

### ISSUE THREAD

**Issue by littlespray** [visinf/irr#34]
Hi,

Thank you for your great work! I used irr's dataloader in my code and it went very well when training. But when inferring, an error will occur:
```RuntimeError: The size of tensor a (39) must match the size of tensor b (40) at non-singleton dimension 3```

It seems there is a problem with the input size. I noticed that in ```scripts/validation/IRR-PWC_kitti.sh```, there is no augumentations like crop. However, there are some variances in the size of images in KITTI dataset(e.g. ```data_stereo_flow/training/image_0/000000_10.png``` is 1226x370, while ```data_stereo_flow/training/image_0/000006_10.png``` is 1242x375). Could you  please tell me how to process KITTI images? Thank you very much!

**Comment by hurjunhwa** [comment]
Hi, thanks a lot!
I think you can bypass the problem by using a mini-batch size of 1, during the inference.
Best,
Jun

**Comment by littlespray** [comment]
> Hi, thanks a lot!
> I think you can bypass the problem by using a mini-batch size of 1, during the inference.
> Best,
> Jun

Hi,

Thank you very much for prompt reply! Actually my inference batch size is 1. It is a little strange. So when inferring on validation set, you didn't do any crop or augmentation and just used the original image?

With regard,
littlespray

**Comment by hurjunhwa** [comment]
When I run the script, it still works without an error.
Yes, no crop / no augmentation during the inference, but just using the original image itself.
Can you maybe track down which line of source code cause the error?

**Comment by hurjunhwa** [comment]
When upsampling flow or occlusion, we resize them to the feature map size instead of doubling the resolution.

https://github.com/visinf/irr/blob/f0eba07773806941853d7cb7f7ad28307a288a20/models/IRR_PWC.py#L81

https://github.com/visinf/irr/blob/f0eba07773806941853d7cb7f7ad28307a288a20/models/flownet_modules.py#L57-L60

I guess this can prevent the resolution mismatch between the upsampled flow/occlusion and the original feature map (x1) when concatenating them.

**Comment by littlespray** [comment]
> When upsampling flow or occlusion, we resize them to the feature map size instead of doubling the resolution.
> 
> https://github.com/visinf/irr/blob/f0eba07773806941853d7cb7f7ad28307a288a20/models/IRR_PWC.py#L81
> 
> https://github.com/visinf/irr/blob/f0eba07773806941853d7cb7f7ad28307a288a20/models/flownet_modules.py#L57-L60
> 
> I guess this can prevent the resolution mismatch between the upsampled flow/occlusion and the original feature map (x1) when concatenating them.

Dear Jun,

I find there is a little difference between your implementation and [NVLab](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/models/PWCNet.py)'s. For example, the input of flow estimator(In line ```213``` of [NVLab](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/models/PWCNet.py)'s implementation, it concats the ```up_feat6``` with ```corr```, ```x_intm``` and ```flow```), and the upsampling module ([NVLab](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/models/PWCNet.py)'s uses deconv). Could you please tell me why you choose to implement in this way?

(The first difference maybe the key to this problem, as I use [NVLab's implementation of PWC-Net](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/models/PWCNet.py) in my code, and the error occured because ```up_feat6``` mismatched with others)

**Comment by hurjunhwa** [comment]
Hi,
It was a design choice. 
Empirically, adding the unsampled feature map from the previous layer (up_feat6) made only a marginal difference.
Thus, I decided to leave it out.
Yes, if the width of the input image is not a factor of 2^n (n is the # of downsampling operations), the mismatch between the widths of upsampled feature map and the original feature map happens, causing such error. 
Best,
Jun

**Comment by littlespray** [comment]
> Hi,
> It was a design choice.
> Empirically, adding the unsampled feature map from the previous layer (up_feat6) made only a marginal difference.
> Thus, I decided to leave it out.
> Yes, if the width of the input image is not a factor of 2^n (n is the # of downsampling operations), the mismatch between the widths of upsampled feature map and the original feature map happens, causing such error.
> Best,
> Jun

Dear Jun,

Thank you for your reply. I got it!
Yes, that is exactly why the mismatch happens.
But I am also wondering why people concat ```corr```,  ```feat```, ```flow```  together. Could you please tell me if there is a theorical explanation? As I am really wondering why they don't use another operataion like ```ADD```, or change the concat order, like concating ```flow```, ```feat```, ```corr``` instead.
 
Besides, could you please share the motivation to replace the deconv module with bilinear when upsampling flow? It is a great idea and it seems that there is no drop in performance!

With regrad,
littlespray

**Comment by hurjunhwa** [comment]
I guess many of the elements are empirically found, lacking theoretical grounds unlike energy-based models back in the day.
You can try to use other operations and see if works better. 
I think understanding what is going inside the architecture can justify the design choices.
The order of concatenation does not matter as they are trained.

The Deconv module is for learning to upscale the feature (or flow) map, can have a more learnable capacity. 
But, I think using either deconv or bininear upsampling wouldn't make a huge difference.

Best,
Jun

**Comment by littlespray** [comment]
> I guess many of the elements are empirically found, lacking theoretical grounds unlike energy-based models back in the day.
> You can try to use other operations and see if works better.
> I think understanding what is going inside the architecture can justify the design choices.
> The order of concatenation does not matter as they are trained.
> 
> The Deconv module is for learning to upscale the feature (or flow) map, can have a more learnable capacity.
> But, I think using either deconv or bilinear upsampling wouldn't make a huge difference.
> 
> Best,
> Jun

Dear Jun,

Got it ! Thank you very much for your patient and prompt answer. And thank you again for sharing such great work.

With regard,
littlespray
