### ISSUE TITLE
how to prepare data for kitti testing

### ISSUE THREAD

**Issue by RokiaAbdeen** [visinf/irr#35]
could you explain please what are these files that required to upload to kitti_2015 (Provide a zip file which contains the 'disp_0' directory (stereo), the 'flow' directory (flow), or the 'disp_0', 'disp_1' and 'flow' directories (scene flow) in its root folder. Use the file format and naming described in the readme.txt (000000_10.png,...,000199_10.png).
how to save them?
thanks in advance..

**Comment by hurjunhwa** [comment]
Hi,

You can find the information of what those files are in the text file of the **development kit** in [KITTI benchmark](http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=flow).
If you want to evaluate optical flow only, you can just upload the **flow** folder.

They are the same format as the KITTI GT data, 16 bit png.
You can get it if you include ``--save_result_png=True`` in the script file.
Or you can use this function,
https://github.com/visinf/irr/blob/f0eba07773806941853d7cb7f7ad28307a288a20/utils/flow.py#L37-L62

Much simpler code can be found here as well:
https://github.com/princeton-vl/RAFT/blob/master/core/utils/frame_utils.py

**Comment by RokiaAbdeen** [comment]
Thanks so much for your reply
I have another problem with kitti_12, I used the same image format as kitti_15 but I got wrong image format 
could you explain please how to write the flow images for kitti_12 benchmark
thanks again

**Comment by hurjunhwa** [comment]
I don't remember clearly since it's been a bit long time ago.
I think it would be the same as KITTI 2015.
Please read the readme file from KITTI 2012 carefully! the answer is there!

**Comment by RokiaAbdeen** [comment]
I have read it , I just needed the pytorch code to write the flow files
the image format is not same as kitti_15, I used the same format but I got image format error
but thank you anyway
