### ISSUE TITLE
Confused by if statement: 'if (f_loss.data > o_loss.data).numpy:'

### ISSUE THREAD

**Issue by ZerenLong** [visinf/irr#36]
Hi authors of irr, thanks for your great work in optical flow estimation.

I am a little confused by this `if` statement in all the loss functions in the repo:

``` python
if (f_loss.data > o_loss.data).numpy:
    f_l_w = 1
    o_l_w = f_loss / o_loss
else:
    f_l_w = o_loss / f_loss
    o_l_w = 1
```

I understand that the code wants to balance flow loss and occ loss. However, `(f_loss.data > o_loss.data).numpy` always return `True` and the program will never go to the `else` statement.

Any help would be appreciated!

**Comment by hurjunhwa** [comment]
Oops, thanks for pointing out the mistake.
Please remove the ```.data``` and ```numpy``` operation, and it will work as intended:

```python
if f_loss > o_loss:
    f_l_w = 1
    o_l_w = f_loss / o_loss
else:
    f_l_w = o_loss / f_loss
    o_l_w = 1
```

Thanks a lot for sharing it!

**Comment by ZerenLong** [comment]
Thanks for your quick reply, hurjunhwa !
