### ISSUE TITLE
Encountered a little problem in the inference phase

### ISSUE THREAD

**Issue by wenshuojie** [visinf/irr#40]
Hi，thanks for your share code, that's great.
But I have some questions. If I want to use some images for inferenceing, what should I do？
Whether it’s in a script in scripts/validation, just fill in the "(YOUR PATH)" field.

```
# datasets
SINTEL_HOME=(YOUR PATH)/MPI-Sintel-complete/
```
Then run XXX.sh

Because I’m just new to deep learning, I don’t know much about the code.

**Comment by hurjunhwa** [comment]
Hi, 

If you want to do the inference on these datasets (KITTI, FlyingThings, FlyingChairs, or KITTI), you can use the script files after filling in the "(YOUR PATH)" field. 
This "(YOUR PATH)" denotes the local directory where the dataset is stored in your machine.

If you want to run on other datasets, you can write a dataloader for your dataset like here: https://github.com/visinf/irr/tree/master/datasets

Or you can also refer to [HERE](https://github.com/visinf/irr/issues/2) that provides a simple python code for the inference!
