### ISSUE TITLE
Camera parameters of Flyingchairs dataset

### ISSUE THREAD

**Issue by xianshunw** [visinf/irr#49]
Hi, thanks for your contribution. 
Recently, we are trying to train our optical flow network on your generated flyingchairs dataset. But our method needs camera parameters as input, could you provide such information for us.

**Comment by hurjunhwa** [comment]
Hi,
The background images used in the dataset are crawled from the web: each image has a different & unknown focal length.

**Comment by xianshunw** [comment]
> Hi, The background images used in the dataset are crawled from the web: each image has a different & unknown focal length.

Well, I wonder if I understand this correctly:
so the background images are just with a random motion directly in the 2D plane, not with a 3D motion in the space and project to the 2D plane?

**Comment by hurjunhwa** [comment]
Yes, the background motion is 2D affine transform. As you said, it would be possible to apply 3D motion & 2D projection, but I guess it requires a per-pixel depth map for each background image? otherwise, it can be equivalent to 2D homography transformation.

**Comment by xianshunw** [comment]
ok, thanks.
