### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by nankeermeng** [visinf/irr#5]
when I test a video, the first frame and the second frame can output optical flow result corrently. However, when read the second frame and the third frame , it output an error RuntimeError: CUDA out of memory. Tried to allocate 140.00 MiB (GPU 0; 10.76 GiB total capacity; 9.70 GiB already allocated; 113.56 MiB free; 185.42 MiB cached), these error locate in  output_dict = model.forward(input_dict)， the detail is :
Traceback (most recent call last):
  File "/irr/demo_vid.py", line 69, in <module>
    output_dict = model.forward(input_dict)
  File "/irr/models/IRR_PWC.py", line 115, in forward
    x_intm_occ_b, occ_res_b = self.occ_estimators(torch.cat([out_corr_relu_b, x2_1by1, occ_b], dim=1))
  File "/Anaconda3/conda3/envs/irr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "irr/irr/models/pwc_modules.py", line 184, in forward
    x5 = torch.cat([self.conv5(x4), x4], dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 140.00 MiB (GPU 0; 10.76 GiB total capacity; 9.70 GiB already allocated; 113.56 MiB free; 185.42 MiB cached) . please help me ,thanks

**Comment by hurjunhwa** [comment]
I think the left-over memory from the previous frame cause the issue.
Have you tried using ``torch.no_grad()``?

**Comment by nankeermeng** [comment]
> I think the left-over memory from the previous frame causes the issue.
> Have you tried using `torch.no_grad()`?

Year, thank you very much , with torch.no_grad(), it has not RuntimeError: CUDA out of memory problem. However, the code run 20 frames, then produce an error：‘ASSERT: "false" in file qasciikey.cpp, line 501’， I donot know why it produce these error.

**Comment by nankeermeng** [comment]
> > I think the left-over memory from the previous frame causes the issue.
> > Have you tried using `torch.no_grad()`?
> 
> Year, thank you very much , with torch.no_grad(), it has not RuntimeError: CUDA out of memory problem. However, the code run 20 frames, then produce an error：‘ASSERT: "false" in file qasciikey.cpp, line 501’， I donot know why it produce these error.

it is the problem that  cv2.imshow('result', flow_to_png_middlebury(flow)), I comment # cv2.imshow('result', flow_to_png_middlebury(flow)), it is ok ,thank you
