### ISSUE TITLE
Sintel occ

### ISSUE THREAD

**Issue by Ecalpal** [visinf/irr#6]
Hi!

I have noticed that the name of sintel occ floder in datasets/sintel.py is occlusions_rev.

https://github.com/visinf/irr/blob/1639c0f17923f09df694f52d3b212b374af6f25c/datasets/sintel.py#L44

It is different from the folder name in the original Sintel dataset(The original is occlusions, but get occlusions_rev here), Did you make any changes on occlusions of sintel?

**Comment by hurjunhwa** [comment]
Hi,

Yes, in the Sintel occlusion ground truth, there are some frames that do not properly consider out-of-bound pixels as occlusion.
Thus we revised the Sintel occlusion grouth truth by using the optical flow ground truth.
You can download the revised version here:

https://www.dropbox.com/s/kwx1s5a8g7r0t2y/occlusions_rev.zip?dl=0

**Comment by Ecalpal** [comment]
Thank you!
